# Inicializando Pré-Processamento

In [2]:
%pip install altair 
%pip install vega_datasets
%pip install pandas
%pip install kagglehub
%pip install os

Requirement already satisfied: altair in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (6.0.0)
Requirement already satisfied: narwhals>=1.27.1 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from altair) (2.18.0)
Requirement already satisfied: packaging in c:\users\crisw\appdata\roaming\python\python310\site-packages (from altair) (26.0)
Requirement already satisfied: jinja2 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from altair) (3.1.6)
Requirement already satisfied: typing-extensions>=4.12.0 in c:\users\crisw\appdata\roaming\python\python310\site-packages (from altair) (4.15.0)
Requirement already satisfied: jsonschema>=3.0 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from altair) (4.26.0)
Requirement already satisfied: attrs>=22.2.0 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=3.0->altair) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=3.0->altair) (2025.9.1)
Requirement already satisfied: rpds-py>=0.25.0 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=3.0->altair) (0.30.0)
Requirement already satisfied: referencing>=0.28.4 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from jsonschema>=3.0->altair) (0.37.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from jinja2->altair) (3.0.3)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\crisw\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: vega_datasets in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (0.9.0)
Requirement already satisfied: pandas in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from vega_datasets) (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from pandas->vega_datasets) (2026.1.post1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\crisw\appdata\roaming\python\python310\site-packages (from pandas->vega_datasets) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from pandas->vega_datasets) (2.2.6)
Requirement already satisfied: tzdata>=2022.7 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from pandas->vega_datasets) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\crisw\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas->vega_datasets) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\crisw\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: pandas in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (2.3.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2026.1.post1)
Requirement already satisfied: numpy>=1.22.4 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.2.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\crisw\appdata\roaming\python\python310\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\crisw\appdata\roaming\python\python310\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\crisw\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Requirement already satisfied: kagglehub in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (1.0.0)
Requirement already satisfied: requests in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from kagglehub) (2.32.5)
Requirement already satisfied: tqdm in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from kagglehub) (4.67.3)
Requirement already satisfied: pyyaml in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from kagglehub) (0.1.16)
Requirement already satisfied: packaging in c:\users\crisw\appdata\roaming\python\python310\site-packages (from kagglehub) (26.0)
Requirement already satisfied: protobuf in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (7.34.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from requests->kagglehub) (3.4.6)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\crisw\appdata\local\programs\python\python310\lib\site-packages (from requests->kagglehub) (2026.2.25)
Requirement already satisfied: colorama in c:\users\crisw\appdata\roaming\python\python310\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\crisw\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

Note: you may need to restart the kernel to use updated packages.

ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'c:\Users\crisw\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.

In [3]:
import pandas as pd
import altair as alt
from vega_datasets import data
import os
import kagglehub
alt.data_transformers.disable_max_rows()

c:\Users\crisw\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

DataTransformerRegistry.enable('default')

In [4]:
# Download latest version
path = kagglehub.dataset_download("suhanigupta04/employee-mental-health-and-burnout-dataset")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\crisw\.cache\kagglehub\datasets\suhanigupta04\employee-mental-health-and-burnout-dataset\versions\1

In [5]:
arquivos = os.listdir(path)
print("Arquivos disponíveis no dataset:",arquivos)

caminho_csv = os.path.join(path, "tech_mental_health_burnout.csv")
df = pd.read_csv(caminho_csv)
df.head()

Arquivos disponíveis no dataset: ['tech_mental_health_burnout.csv']

,age,gender,job_role,experience_years,company_size,work_mode,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,...,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,burnout_level,seeks_professional_help
0,50,Female,Backend Developer,7.8,Large,Hybrid,45.0,0.0,5.0,0,...,8.6,1,4.4,0,4.8,4.3,2.6,1.0,Low,0
1,36,Male,Frontend Developer,1.8,Mid-size,Remote,56.0,4.0,6.0,0,...,11.5,4,4.1,0,6.7,4.8,4.6,3.7,Moderate,0
2,29,Male,DevOps,2.5,MNC,Hybrid,43.0,2.0,6.0,3,...,6.8,3,6.5,0,4.5,4.0,2.5,1.0,Low,0
3,42,Female,Backend Developer,1.5,Mid-size,Hybrid,57.0,9.0,4.0,1,...,10.2,5,2.5,0,6.1,5.8,1.8,3.6,Moderate,0
4,40,Female,Frontend Developer,3.4,Large,Remote,49.0,0.0,3.0,4,...,11.9,5,4.6,0,7.2,5.9,2.4,3.5,Low,0

In [6]:
df.describe()

,age,experience_years,work_hours_per_week,overtime_hours,meetings_per_day,deadlines_missed,job_satisfaction,manager_support,work_life_balance,sleep_hours,physical_activity_days,screen_time_hours,caffeine_intake,social_support_score,has_therapy,stress_level,anxiety_score,depression_score,burnout_score,seeks_professional_help
count,150000.000000,150000.000000,150000.00000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000,150000.000000
mean,38.025340,5.055010,47.00758,6.127180,4.010893,1.284193,5.500248,5.497537,5.016357,6.499120,2.599833,8.002713,2.101693,5.498163,0.251133,5.785428,4.523763,3.096687,2.114121,0.096333
std,9.510609,2.878602,7.89331,3.783618,1.978316,1.426264,1.956102,1.956915,1.948553,1.192343,1.814880,1.987813,1.300247,1.957432,0.433667,1.331506,1.201506,1.187668,1.112614,0.295049
min,22.000000,0.000000,30.00000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3.000000,0.000000,3.000000,0.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000
25%,30.000000,3.000000,42.00000,3.000000,3.000000,0.000000,4.200000,4.100000,3.700000,5.700000,1.000000,6.700000,1.000000,4.200000,0.000000,4.900000,3.700000,2.200000,1.000000,0.000000
50%,38.000000,5.000000,47.00000,6.000000,4.000000,1.000000,5.500000,5.500000,5.000000,6.500000,2.000000,8.000000,2.000000,5.500000,0.000000,5.800000,4.500000,3.100000,1.900000,0.000000
75%,46.000000,7.000000,52.00000,9.000000,5.000000,2.000000,6.900000,6.800000,6.400000,7.300000,4.000000,9.300000,3.000000,6.800000,1.000000,6.700000,5.300000,3.900000,2.800000,0.000000
max,54.000000,18.500000,84.00000,24.000000,12.000000,5.000000,10.000000,10.000000,10.000000,10.000000,7.000000,16.000000,5.000000,10.000000,1.000000,10.000000,9.600000,8.100000,8.100000,1.000000

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 25 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   age                      150000 non-null  int64
 1   gender                   150000 non-null  object
 2   job_role                 150000 non-null  object
 3   experience_years         150000 non-null  float64
 4   company_size             150000 non-null  object
 5   work_mode                150000 non-null  object
 6   work_hours_per_week      150000 non-null  float64
 7   overtime_hours           150000 non-null  float64
 8   meetings_per_day         150000 non-null  float64
 9   deadlines_missed         150000 non-null  int64
 10  job_satisfaction         150000 non-null  float64
 11  manager_support          150000 non-null  float64
 12  work_life_balance        150000 non-null  float64
 13  sleep_hours              150000 non-null  float64
 14  physical_activity_days   150000 non-null  int64
 15  screen_time_hours        150000 non-null  float64
 16  caffeine_intake          150000 non-null  int64
 17  social_support_score     150000 non-null  float64
 18  has_therapy              150000 non-null  int64
 19  stress_level             150000 non-null  float64
 20  anxiety_score            150000 non-null  float64
 21  depression_score         150000 non-null  float64
 22  burnout_score            150000 non-null  float64
 23  burnout_level            150000 non-null  object
 24  seeks_professional_help  150000 non-null  int64
dtypes: float64(14), int64(6), object(5)
memory usage: 28.6+ MB

In [18]:
# Filter data for burnout score >= 6
filtered_df = df[df['stress_level'] >= 6]

# Group by Work_Mode and count
burnout_by_mode = filtered_df.groupby('work_mode').size().reset_index(name='Count')

# Create bar chart with Altair
chart = alt.Chart(burnout_by_mode).mark_bar().encode(
    x='work_mode:N',
    y='Count:Q',
    tooltip=['work_mode', 'Count']
).properties(
    title='Stress Level >= 6 by Work Mode'
)

chart.display()

alt.Chart(...)

In [20]:
work_mode_counts = df['work_mode'].value_counts().reset_index(name='Count').rename(columns={'index': 'work_mode'})

alt.Chart(work_mode_counts).mark_bar().encode(
    x='work_mode:N',
    y='Count:Q',
    tooltip=['work_mode', 'Count']
).properties(
    title='Number of Employees per Work Mode'
).display()

alt.Chart(...)

In [19]:
# Filter data for stress level >= 6
filtered_df = df[df['stress_level'] >= 6]

# Group by Company_Size and count
burnout_by_size = filtered_df.groupby('company_size').size().reset_index(name='Count')

# Create bar chart with Altair
chart = alt.Chart(burnout_by_size).mark_bar().encode(
    x='company_size:N',
    y='Count:Q',
    tooltip=['company_size', 'Count']
).properties(
    title='Stress Level >= 6 by Company Size'
)

chart.display()

alt.Chart(...)